dtm-labs/dtm

- .gitignore
- README.md
> fix/readme: add space for compatibility of different markdown renderer

- common/types.go
- dtmgrpc/dtmgrpc.proto
> 1.cont always not nil .  2.fix typo

- dtmcli/consts.go
> [ISSUe #60] fix var 

- dtmsvr/dtmsvr.go
- dtmsvr/trans_status.go
[#59 ](https://github.com/yedf/dtm/issues/59)
> fix:to change update_time

- bench/http.go
- dtmcli/barrier.go
- dtmcli/dtmimp/types.go
- dtmcli/types.go
- examples/grpc_saga_barrier.go
- examples/http_saga_barrier.go
- examples/http_saga_gorm_barrier.go
- examples/http_tcc_barrier.go
- test/base_test.go
- test/tcc_barrier_test.go
barrier interface change to sql.Tx
> barrier interface change to sql.Tx

- common/db.go
- dtmcli/dtmimp/utils.go
> 1.fix LogRedf

- common/types.go
- dtmsvr/api_http.go
- dtmsvr/dtmsvr.go
- dtmsvr/metrics.go
Fix： https://github.com/yedf/dtm/issues/76
> fix(server): use http as prom server

- common/config.go
- common/config_test.go
- go.mod
- go.sum
> 添加mysql配置参数校验

- dtmsvr/storage/boltdb.go
Fix： https://github.com/yedf/dtm/issues/106
在初始化 boltdb 时确保 bucket 已经存在（虽然在 PopulateData 中会去创建 Bucket，但是貌似传递的参数都是 true）
> fix: ensure the buckets is exists when use boltdb

- .gitignore
- .golangci.yml
- Makefile
Fix: https://github.com/yedf/dtm/issues/109
> fix: add Makefile for test/lint

- dtmcli/dtmimp/utils.go
翻译dtmcli/dtmimp/utils.go里面的中文成英文
> translate utils.go

- .travis.yml
- dtmsvr/storage/boltdb.go
- dtmsvr/storage/boltdb_test.go
- go.mod
Fix: https://github.com/yedf/dtm/issues/92
> fix: add cleanup when bolt storage startup

- common/config_test.go
- dtmsvr/storage/boltdb.go
- dtmsvr/storage/store.go
- test/msg_test.go
- test/saga_concurrent_test.go
boltdb is slow, and some test result changed. now fixed
> Test passed

- app/main.go
- bench/main.go
- dtmsvr/storage/boltdb/boltdb.go
- dtmsvr/storage/boltdb/boltdb_test.go
- dtmsvr/storage/registry/registry.go
- dtmsvr/storage/store.go
- dtmsvr/utils.go
- test/store_test.go
将 storage 拆分到不同的 pkg 里面，避免各种 impl 混合在一起，不利于管理
> refactor(*): split storage to different package

- dtmcli/dtmimp/trans_xa_base.go
翻译 dtmcli/dtmimp/trans_xa_base.go 中文注释
> translate trans_xa_base.go

- common/config.go
- common/db.go
- dtmcli/dtmimp/types.go
- dtmcli/dtmimp/utils.go
- dtmsvr/storage/boltdb/boltdb.go
- dtmsvr/storage/boltdb/boltdb_test.go
- go.mod
- go.sum
> add license

- dtmcli/tcc.go
> translate dtmcli/tcc.go

- helper/Dockerfile-release
在 k8s 中，可以更方便的设置参数。
before:
```yaml
name: dtm-server
image: yedf/dtm:1.8.1
imagePullPolicy: IfNotPresent
command:
["/app/dtm/dtm", "-c", "/app/dtm/configs/config.yaml"]
```
after:
```yaml
name: dtm-server
image: yedf/dtm:1.8.1
imagePullPolicy: IfNotPresent
args:
- "-c=/app/dtm/configs/config.yaml"
```
> use ENTRYPOINT instead of CMD

- dtmsvr/svr.go
- dtmsvr/trans_status.go
- dtmsvr/trans_type_saga.go
- dtmsvr/utils.go
- sqls/dtmsvr.storage.tdsql.sql
TDSQL数据分片是按照指定的shardkey进行分区的，使用过程中主要的注意点：
1）主键key必须要包含shardkey，因此建表时候这里是由id和gid构成primary key
2）查询或者更新最好带上shardkey，否则会进行所有分片查询
3) 原先更新分支事务是通过主键id更新在分布式数据库tdsql场景下，如果不加上gid会生成新的记录，因此异步更新分支事务需要添加gid查询条件
> feature:support tencent distributed database tdsql

- dtmcli/logger/log.go
- dtmcli/logger/logger_test.go
- dtmsvr/config/config.go
- dtmsvr/config/config_utils.go
- go.mod
- go.sum
- test/store_test.go
实现 https://github.com/dtm-labs/dtm/issues/153
> add logger interface defination

- dtmsvr/config/config.go
> fix config spell

- bench/main.go
- conf.sample.yml
- dtmcli/logger/log.go
- dtmcli/logger/logger_test.go
- dtmsvr/config/config.go
- dtmsvr/svr.go
- go.mod
- main.go
> Revert "Write log to file"

- bench/main.go
- conf.sample.yml
- dtmcli/logger/log.go
- dtmcli/logger/logger_test.go
- dtmsvr/config/config.go
- dtmsvr/svr.go
- go.mod
- main.go
- test/main_test.go
> Write log to file

- dtmgrpc/dtmgimp/grpc_clients.go
- dtmsvr/metrics.go
- dtmsvr/svr.go
- go.mod
- go.sum
Add metrics on list below:
- dtm_server_info
- dtm_transaction_handled_duration
> more metrics for dtm server

- conf.sample.yml
- dtmcli/logger/log.go
- dtmcli/logger/logger_test.go
> optimize the output config of log 

- dtmcli/saga.go
- dtmgrpc/saga.go
- dtmsvr/trans_class.go
> 支持grpc下SAGA的并发执行

- dtmcli/dtmimp/utils.go
issue 优化dtm在docker中的网络请求 [https://github.com/dtm-labs/dtm/issues/206](url)
> MayReplaceLocalhost替换127.0.0.1

- .github/workflows/release.yml
```yaml
on:
create:
tags:
- 'v*.*.*'
```
create events 没有筛选 branch or tag 功能, 导致 create 任意 branch or tag , 都会触发执行
Create events docs
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#create
Push events docs
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
> fix release workflows trigger events

- dtmsvr/api_http.go
- dtmsvr/storage/boltdb/boltdb.go
- dtmsvr/storage/redis/redis.go
- dtmsvr/storage/sql/sql.go
- dtmsvr/storage/store.go
- test/api_test.go
- test/store_test.go
> support reset crontime 

- dtmsvr/storage/sql/sql.go
> add Copyright

- dtmcli/dtmimp/trans_base.go
- dtmcli/saga.go
- dtmgrpc/saga.go
- dtmsvr/trans_type_msg.go
- test/msg_options_test.go
- test/saga_concurrent_test.go
https://github.com/dtm-labs/dtm/issues/207
> feat:msg support concurrent

- conf.sample.yml
issues：250
conf.sample.yml配置缺了个冒号 #250
> fix conf.sample.yml

- dtmcli/dtmimp/trans_base.go
> fix: The requestTimeout setting is invalid

- .gitignore
- conf.sample.yml
- dtmcli/dtmimp/vars.go
- dtmsvr/config/config.go
- dtmsvr/microservices/drivers.go
- dtmsvr/svr.go
- dtmsvr/trans_status.go
- go.mod
- go.sum
- main.go
currently support nacos. others may be add soon
> Add spring cloud support. 

- dtmsvr/storage/trans.go
- dtmsvr/trans_status.go
- dtmsvr/trans_type_tcc.go
- dtmsvr/trans_type_xa.go
- go.sum
- sqls/dtmsvr.storage.mysql.sql
- sqls/dtmsvr.storage.postgres.sql
- sqls/dtmsvr.storage.tdsql.sql
- test/dtmsvr_test.go
- test/tcc_test.go
- test/xa_test.go
> Support rollback_reason for global transaction

- dtmgrpc/type.go
- dtmsvr/storage/trans.go
- dtmsvr/trans_status.go
- dtmsvr/trans_type_saga.go
- test/busi/base_types.go
- test/busi/busi.go
- test/saga_grpc_test.go
- test/saga_options_test.go
- test/saga_test.go
- test/types.go
#292
#310 
现有的 rollback_reason
- Timeout after %d seconds
- Transaction branch execution failed
是否需要使用常量进行管理 rollback_reason？
> [WIP]Support rollback_reason for saga

- dtmcli/dtmimp/utils.go
- dtmsvr/trans_status.go
> Support rollback_reason for JSONRPC 

- dtmcli/dtmimp/trans_base.go
- dtmcli/tcc.go
- dtmgrpc/dtmgpb/dtmgimp.proto
- dtmgrpc/tcc.go
- dtmsvr/api.go
- test/tcc_test.go
> Support rollback_reason for tcc transaction

- README.md
- helper/README-en.md
- test/busi/quick_start.go
subtraction -> sub-transaction
> docs: correct spelling

- client/dtmgrpc/dtmgimp/types.go
- client/dtmgrpc/msg.go
- client/dtmgrpc/tcc.go
- client/dtmgrpc/xa.go
callBranch 增加callOptions参数，用于 metadata 接收场景等
> feature: callBranch 增加callOption 参数

- client/dtmcli/dtmimp/trans_base.go
- dtmsvr/trans_type_saga.go
- test/busi/base_http.go
- test/saga_options_test.go
> feat: Support Saga options RetryLimit

- dtmsvr/trans_status.go
> Rename to `determineHTTPRequestMethod`

- client/dtmcli/dtmimp/types.go
- client/dtmcli/dtmimp/utils.go
- conf.sample.yml
- dtmsvr/config/config.go
- dtmsvr/config/config_test.go
- dtmsvr/config/config_utils.go
modified:   client/dtmcli/dtmimp/types.go
modified:   client/dtmcli/dtmimp/utils.go
modified:   conf.sample.yml
modified:   dtmsvr/config/config.go
modified:   dtmsvr/config/config_test.go
modified:   dtmsvr/config/config_utils.go
> feat: add postgres schema config support

- client/dtmgrpc/dtmgimp/utils.go
grpc request support custom metadata
> feat:cli support custom grpc metadata

- client/dtmgrpc/xa.go
> 修复xa grpc 事务无法携带header 等信息的问题

- client/dtmcli/dtmimp/utils.go
current implementation of `PooledDB` is unsafe
close https://github.com/dtm-labs/client/pull/2
> fix pooled db concurrency bug

- go.mod
- go.sum
upgrade to go1.18 from go1.16
and ran > go mod tidy
> upgrade to go1.18

- charts/values.yaml
> feat: upgrade image version

- admin/src/views/Dashboard/GlobalTransactions/AllTransactions.vue
1. Add time related columns
2. Table horizontal scrolling
3. Put the action in the first column
> Add time related columns, put the action in the first column

- dtmsvr/api_http.go
- dtmsvr/storage/boltdb/boltdb.go
- dtmsvr/storage/redis/redis.go
- dtmsvr/storage/sql/sql.go
- dtmsvr/storage/store.go
prepare four conditions placeholder for admin query list.
除了按分页查trans，本次增加了按更多条件查询，创建了一个struct来传递越来越复杂的查询条件，现在里面的四个查询条件只是占位，若允许使用struct则PR后再实现这四个查询属性，或再按照需求添加其他查询条件。
> Add TransGlobalScanCondition struct for admin api all trans scan

- admin/src/components.d.ts
- admin/src/views/Dashboard/GlobalTransactions/_Components/DialogTransactionDetail.vue
Details in the three commits.
TODO: action in dialog
preview:
> Feature trans detail dialog optimize

- sqls/dtmsvr.storage.mysql.sql
TDSql的建表脚本是否还持续维护中， 里面的注释和列甚至表都没有跟进上。
> Fix mysql dtm.trans_global status column comment.

- client/dtmcli/trans_saga.go
- client/dtmgrpc/options_test.go
- client/dtmgrpc/saga.go
- dtmsvr/trans_class.go
- dtmsvr/trans_process.go
- dtmsvr/trans_status.go
- dtmsvr/trans_type_msg.go
- dtmsvr/trans_type_saga.go
- dtmsvr/trans_type_tcc.go
- dtmsvr/trans_type_workflow.go
- dtmsvr/trans_type_xa.go
- dtmsvr/utils.go
- dtmsvr/utils_test.go
- test/saga_grpc_test.go
close #454 
Due to the involvement of multiple APIs, the preliminary intention is to incorporate the NewSagaGrpcWithContext as an elective invocatory approach. In due course, I shall append illustrative instances and examinations. The subsequent objective encompasses an endeavor to embrace support for opentelemetry.
> feat: new saga grpc with context

- go.mod
- go.sum
see https://github.com/dtm-labs/dtmdriver-kratos/pull/8
> upgrade kratos driver to use discovery

- dtmsvr/microservices/drivers.go
- go.mod
- go.sum
A microservices framework sponge driver added to dtm for service registration and discovery.
> feat: add driver sponge

- go.mod
- go.sum
To fix following issue:
Vulnerability found in dependency:
CVE-2024-24786
7.5
Loop with Unreachable Exit Condition ("Infinite Loop") vulnerability with High severity found
Show details…
> feat(common): upgrade protobuf from 1.31.0 to 1.34.1

- dtmsvr/config/config.go
- dtmsvr/config/config_test.go
> feat(config): Set UpdateBranchSync default value as 1 in config struct

- .github/workflows/tests.yml
- helper/compose.store.yml
- Update MySQL image from 5.7 to 8 in GitHub Actions workflow
- Update MySQL image from 5.7 to 8 in Docker Compose file
> build(mysql): update MySQL version to 8
