- app/main.go
dtm [commands], here commands contain dtmsvr, dev, quick_start, qs and examples' names.
Before, we use `fmt.Sprintf("%-{n}s",...)` to align the commands' names, we could use `tabwriter` to do this instead:
- alignment will works normally, even the examples' names changed or new examples added;
- make main logic clearer;
> refactor: align the output commands

- docker-compose.yml
使用docker-compose部署环境时：要求容器内的Mysql、dtm服务端与宿主机的时间和时区保持一致，这样不会因为时间问题，而造成事务调度异常。
> 修改docker-compose.yml：使容器内时间和时区设置与宿主机保持一致

- helper/Dockerfile-release
1. `GO111MODULE` is default to on from version 1.16
2. use `upx` to reduce binary size
> build: remove go env GO111MODULE, add upx to reduce image size

- app/main.go
- common/types.go
- conf.sample.yml
- go.mod
- go.sum
1. support to config db conn，two purposes:
a) reduce cpu loss caused by connection establishment
b) reduce connection network wait time
2. in the container scenario, use uber/automaxprocs to reduce the time-consuming cpu scheduling
> performance optimization

- dtmcli/dtmimp/utils.go
- 跳过一个 caller, 不然的话打印的 caller 始终是 utils
应该把 logger 模块独立出来？不然现在 dtmsvr 打印日志还需要 import dtmcli/dtmimp 包，挺奇怪的
> fix: add callerskip with 1

- .github/workflows/tests.yml
- go.mod
- go.sum
- helper/Dockerfile-release
统一升级至 Go 的次新版本: **1.16**
Go 1.15 End of life at **2021-08-11**
> keep Go version consistent

- .github/workflows/tests.yml
- .golangci.yml
- bench/main.go
- bench/svr/http.go
除了test目录之外的ci error基本修复完成，现为了防止在修复test过程中，其他模块新增又额外新增，先把CI lint的Action打开，并修改.golangci-lint的配置文件，将test目录跳过，带test修完之后，可关闭该配置项
> fix bench ci error and enable ci lint github action

- conf.sample.yml
- dtmsvr/config/config.go
- dtmsvr/svr.go
随着DTM单实例的TPS增加，异步分支更新数量增加，如果异步更新分支状态消费协程消费能力跟不上，则会导致channel上生产消息出现阻塞进而导致请求时延增大，最终会影响整体吞吐量；
这里异步协程配置数量，可以简单采用下面的公式计算：
1）单个异步协程每秒处理的分支数量：1000/一次批量处理分支事务更新时间（单位ms）* 20（每次批量操作更新的分支数）
2）异步协程配置数量：每秒TPS*分支事务数量/(单个异步协程每秒处理的分支数量)
> optimization: config async update branch goroutine num

- charts/templates/deployment.yaml
修复安装 charts 时指定了 `dtm` 以外的名字，导致 deployment 挂载 configmap 失败。
> fix helm deployment mount configMap name

- dtmsvr/storage/registry/registry.go
When the store is not started, the program has no output and is blocked in `WaitStoreUp`, and the problem cannot be detected in time.
> optimize wait store up log

- dtmcli/dtmimp/trans_base.go
- dtmgrpc/dtmgimp/types.go
- dtmgrpc/dtmgimp/utils.go
- dtmsvr/trans_status.go
通过修改TransOptions 结构体，增加Ctx 字段，在grpc invoke时设置 ctx值。
采用这个方式，最大限度的减少代码的改动，不影响原先使用dtm开发者代码使用方式。
```go
dtmgrpc.XaGlobalTransaction(serverAddr, gid, func(xa *dtmgrpc.XaGrpc) error {
xa.BranchHeaders = map[string]string{
"lang": metautils.ExtractIncoming(ctx).Get("lang"),
}
xa.Ctx = ctx
}
```
在需要传递ctx的时候，仿照设置BranchHeaders ，设置下ctx即可
> feat: grpc invoke 增加ctx传递，以用于opentrace 需求

- dtmcli/dtmimp/types.go
- dtmcli/dtmimp/utils.go
DBConf增加DB配置。
主要原因是在 postgresql 使用上不是很方便，有时候在测试环境下可能只有一个账户，但是dtm默认的配置需要 一个用户对应一个db.在开发的时候很不方便，一个微服务的db都要单独设置和创建用户。如果有几十个微服务db就要创建几十个帐号。在开发阶段确实很难受。
> feat: DBConf增加DB配置

- main.go
Use chan to watch exit event instead of `select{}`
In the feature `exit hook feature` or `graceful stop` may be provided in this way..
> add notify channel when exit

- dtmsvr/trans_status.go
- dtmutil/utils.go
This PR is fixing the problem of the DTM server misdetermining a branch action with a "GET" request as a "POST" request due to the `BinPayload` being an empty byte array but not `nil`.
> Make the nil and empty of the `BinPayload` equivalent

- client/workflow/workflow.go
Hi, that conversion is causing a panic when the result of `Value()` is nil
> Fix worflow conversion

- client/workflow/workflow.go
- test/workflow_interceptor_test.go
In a previous PR, I fixed a panic occuring when the client is not used inside saga.
Now, I noticed that returning nil when no `Worfklow` is found has the effect of skipping the grpc call, which is not what we want when we use the client outside saga: client should behave like if no interceptor was there outside saga.
@yedf2: can you confirm that calling invoker the way I'm doing has the effect of completing the call?
> Call invoker if Workflow is nil

- main.go
The original PR https://github.com/dtm-labs/dtm/pull/395 breaks admin proxy
The poxy hosts(cn-admin.dtm.pub/admin.dtm.pub) are static server only, so we should modify the reversed proxy html variable according to configuration
This is a quick fix, new release is required for DTM v1.17.0 users
> fix admin proxy

- .github/workflows/tests.yml
- client/dtmcli/consts.go
- client/dtmcli/dtmimp/consts.go
- client/dtmcli/dtmimp/db_special.go
- client/dtmcli/dtmimp/utils.go
- dtmsvr/config/config.go
- dtmsvr/storage/registry/registry.go
- dtmsvr/storage/sql/sql.go
- dtmutil/db.go
- go.mod
- go.sum
- helper/compose.store.yml
- helper/test-cover.sh
- sqls/dtmsvr.storage.sqlserver.sql
- test/main_test.go
Import gorm.io/driver/sqlserver@v1.1.2 to implement SqlServer storage for dtm server.  
NOT  implement dtmcli go client SqlServer barrier.
#472
> Feature storage sqlserver

- client/dtmcli/barrier_redis.go
- conf.sample.yml
- dtmsvr/storage/redis/redis.go
- go.mod
- go.sum
- test/busi/base_types.go
- test/busi/utils.go
This PR will close request #507 .
Please have a look. thanks!
> feat(common): add redis cluster support

- client/dtmgrpc/dtmgimp/utils.go
goos: windows
goarch: amd64
pkg: [github.com/dtm-labs/dtm/client/dtmgrpc/dtmgimp](http://github.com/dtm-labs/dtm/client/dtmgrpc/dtmgimp)
cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
BenchmarkMap2Kvs
BenchmarkMap2Kvs-16    	  61436	   19822 ns/op
BenchmarkMap2KvsOld
BenchmarkMap2KvsOld-16  	  30886	   38553 ns/op
PASS
```go
package dtmgimp
import (
"math/rand"
"testing"
)
const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
func RandStringBytes(n int) string {
b := make([]byte, n)
for i := range b {
b[i] = letterBytes[rand.Intn(len(letterBytes))]
}
return string(b)
}
var m = func() map[string]string {
m := make(map[string]string)
for i := 0; i < 1000; i++ {
m[RandStringBytes(100)] = "exist"
}
return m
}()
// Map2Kvs map to metadata kv
func Map2KvsNew(m …
```
> Optimize Map2Kvs functions by pre-allocating memory
